image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - eamodio.gitlens
    - redhat.vscode-commons
    - gabrielbb.vscode-lombok
    - ryanluker.vscode-coverage-gutters
    - vscjava.vscode-java-test
    - wmanth.jar-viewer
